# Generated by Django 4.2.3 on 2023-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='slug'),
        ),
    ]
