# Generated by Django 4.2.3 on 2023-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_blog_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Количество просмотров'),
        ),
    ]
