# Generated by Django 4.2.3 on 2023-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_blog_views_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
